version: '3.8'

services:
  nagios:
    image: jasonrivers/nagios:latest
    container_name: nagios
    ports:
      - "8080:80"
    volumes:
      - ./nagios/etc:/opt/nagios/etc
      - ./nagios/var:/opt/nagios/var
      - ./nagios/objects:/opt/objects
    environment:
      - NAGIOS_FQDN=nagios.local
    restart: unless-stopped
EOF